name: Build
on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: snapshot

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/component-descriptor.yaml@master
    needs:
      - build
    permissions:
      id-token: write
